const Type = {
  GET_DATA: 'GET_DATA',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  EDIT: 'EDIT',
  EDIT_ID: 'EDIT_ID',
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  STOP_UPDATE_DATA: 'STOP_UPDATE_DATA',
  SEND_UPDATE: 'SEND_UPDATE'
}
export default Type
